Plugin system 1.1
tom114/irida pull request #38
Opened 2020-05-17 00:35 UTC by tom114

## Description of changes
What did you change in this pull request?  Provide a description of files changed, user interactions changed, etc.  Include how to test your changes.

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

2020-11-27 21:14 UTC, apetkau requested changes
This looks great. Thanks @tom114 . Just two small changes.

2020-11-27 21:19 UTC, tom114 commented on doc/administrator/upgrades/index.md
> +* The plugin's `AnalysisSampleUpdater` implementation.  This will need to change any methods interacting with sample metadata to use the new service methods.
Thanks Aaron.  Updated in 1fd4abe6e2

2020-11-27 21:20 UTC, tom114 commented on doc/administrator/upgrades/index.md
> +* The `pom.xml` file.  This will tell your IRIDA plugin to target the `21.01` version of IRIDA's code in order to take advantage of the new features.  You will also need to increment your plugin vers
Thanks Aaron.  Updated in 1fd4abe6e2

2020-11-27 22:29 UTC, apetkau approved these changes

2020-11-30 15:39 UTC, apetkau commented
Looks good. Thanks.

2020-11-30 15:39 UTC, merged