User group metadata role
tom114/irida pull request #63
Opened 2021-08-19 20:53 UTC by tom114

## Description of changes
What did you change in this pull request?  Provide a description of files changed, user interactions changed, etc.  Include how to test your changes.

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

2021-10-27 23:36 UTC, deepsidhu85 requested changes
Nice work @tom114! Looking great. Just a few comments below

2021-10-27 23:36 UTC, deepsidhu85 commented on src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/metadata/ReadMetadataEntryPermission.java
> +	private ProjectMetadataRole getMaxMetadataRoleForUserAndGroups(ProjectUserJoin userJoin,
Add a javadoc for this private method please

2021-10-27 23:36 UTC, deepsidhu85 commented on src/main/java/ca/corefacility/bioinformatics/irida/service/ProjectService.java
> +	 * @param role         the role that the user plays on the {@link Project}.
Change `plays` to `has`

2021-10-28 18:45 UTC, tom114 commented on src/main/java/ca/corefacility/bioinformatics/irida/service/ProjectService.java
> +	 * @param role         the role that the user plays on the {@link Project}.
Changed the wording in 14e4649

2021-10-28 18:46 UTC, tom114 commented on src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/metadata/ReadMetadataEntryPermission.java
> +	private ProjectMetadataRole getMaxMetadataRoleForUserAndGroups(ProjectUserJoin userJoin,
Saw that this method wasn't even used anymore.  It was replaced by `ProjectMetadataRole.getMaxRoleForProjectAndGroups`.  It's commented in there.

Removed in 60f6d87

2021-11-01 16:09 UTC, joshsadam commented
I don't think I have anything to add to this.  Looks good Tom.  Thanks for putting it together.

2021-11-01 16:32 UTC, deepsidhu85 commented on src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/metadata/ReadMetadataEntryPermission.java
> +	private ProjectMetadataRole getMaxMetadataRoleForUserAndGroups(ProjectUserJoin userJoin,
Thanks!

2021-11-01 16:32 UTC, deepsidhu85 approved these changes

2021-11-01 18:35 UTC, joshsadam approved these changes

2021-11-02 16:27 UTC, merged