Separate metadata role UI for project Members
tom114/irida pull request #65
Opened 2021-10-15 16:03 UTC by joshsadam

## Description of changes

Added UI for selecting metadata roles both when adding and updating a current member.

## Related issue

N/A

## Checklist

Things for the developer to confirm they've done before the PR should be accepted:

*   [ ] ~CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.~
*   [ ] ~Tests added (or description of how to test) for any new features.~
*   [ ] ~User documentation updated for UI or technical changes.~

2021-10-22 17:01 UTC, tom114 requested changes

2021-10-22 17:01 UTC, tom114 commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIMetadataService.java
> +	private final List<String> METADATA_ROLES = ImmutableList.of("LEVEL_1", "LEVEL_2", "LEVEL_3", "LEVEL_4");
Rather than listing them here, can you list the `ProjectMetadataRole.values()`?  That would be better than defining them by string here.

2021-10-22 19:00 UTC, joshsadam commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIMetadataService.java
> +	private final List<String> METADATA_ROLES = ImmutableList.of("LEVEL_1", "LEVEL_2", "LEVEL_3", "LEVEL_4");
Updated in 150fb76

2021-10-25 14:36 UTC, tom114 approved these changes

2021-10-25 14:37 UTC, merged